### ISSUE TITLE
Error status code is incorrectly handled on frontend

### ISSUE THREAD

**Issue by agilob** [apache/pulsar-manager#251] opened 2020-01-22 11:45 UTC
:)

![image](https://user-images.githubusercontent.com/2544251/72891683-ac6dcb80-3d0c-11ea-9a1d-36509b6d052f.png)

**Comment by tuteng** [comment] 2020-02-04 13:06
The same with https://github.com/apache/pulsar-manager/issues/250, close it

**Comment by agilob** [comment] 2020-02-04 15:11
It's not the same, any other error/crash on backend makes frontend behave this way. What this describes is how error on backend is handled on frontend. From screenshot it clearly shows it's not handled nicely. Showing HTML code instead description of error? What are users supposed do it with it? Copy content, paste into index.html and open in a browser tab to read it?

**Comment by agilob** [comment] 2020-02-04 20:43
![image](https://user-images.githubusercontent.com/2544251/73785290-ecae5e80-478e-11ea-87e5-78d677fef30b.png)

**Comment by tuteng** [comment] 2020-02-05 03:03
Got it, reopen it.

**Comment by tuteng** [comment] 2020-02-05 03:11
Can you show some more detailed information, such as which page, which operation to perform, this error seems to be thrown in multiple places in pulsar? https://github.com/apache/pulsar/issues?utf8=%E2%9C%93&q=badversion

**Comment by agilob** [comment] 2020-02-05 08:39
Content of the error is unrelated to what this issue is about so I opened new issue for the badVersion exception #259

**Comment by tuteng** [comment] 2020-02-05 09:34
Can the top error be reproduced and can more detailed information be displayed, such as pulsar-manager's log? @agilob

**Comment by agilob** [comment] 2020-02-05 09:46
>Can the top error be reproduced and can more detailed information be displayed, such as pulsar-manager's log?

The top level error was related to the database problem we solved before.

**Comment by tuteng** [comment] 2020-02-05 10:17
Can I close this？

**Comment by agilob** [comment] 2020-02-05 10:58
Scroll up to https://github.com/apache/pulsar-manager/issues/251#issuecomment-581955745

**Closed** 2023-04-01 16:18 UTC
Labels: area/frontend, triage/week-4
