### ISSUE TITLE
enable client certificate authentication

### ISSUE THREAD

**Issue by alexku7** [apache/pulsar-manager#346] opened 2020-10-16 21:48 UTC
Hello
Our pulsar broker require the client certificate authentication over TLS

Seems that the pulsar manager can't connect to the broker due to the lack certificate authentication support.
Could we ask to add the certificate authentication support between the pulsar manager and the brokers ?

**Comment by tuteng** [comment] 2020-10-17 01:02
https://github.com/apache/pulsar-manager/tree/master/src#enable-https-forward You can set certificate by this document @alexku7

**Comment by alexku7** [comment] 2020-10-17 11:03
Thanks @tuteng 
As I understood , that is intended for HTTPS , I mean traffic encryption but not for the authentication.
I will try again to read and implement these instructions for the authentication as well.
Thanks

**Comment by alexku7** [comment] 2020-10-17 15:13
@tuteng 
Unfortunately it is not working
I tried to do the double check again but it seems this feature is intended to tls encryption traffic in case it's required by brokers.

But if , in addition to the tls encryption, we require the client authentication, it's failed with error 

[io-7750-exec-10] o.apache.pulsar.manager.utils.HttpUtil   : http request exception message: Received fatal alert: bad_certificate, http request error stack: null

And it seems , actually is not implemented in the 
https://github.com/apache/pulsar-manager/blob/73f185c7852d45cbfe6ed386972ffe9058ffffe5/src/main/java/org/apache/pulsar/manager/utils/HttpUtil.java#L92


Even , i tried to import client keys and certificates...still the same error :(

**Comment by tuteng** [comment] 2020-10-18 04:15
I'm very sorry. I misunderstood you. There is a similar issue https://github.com/apache/pulsar-manager/issues/310. I'll take the time to have a look @alexku7

**Comment by alexku7** [comment] 2020-10-18 08:12
@tuteng  Thank you :)

**Comment by sijie** [comment] 2020-10-22 19:16
Close this issue since it is a duplicate of #310

**Closed by sijie** 2020-10-22 19:16 UTC
